version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
     TZ: Asia/Tokyo
    env_file:
      - ./.env
  app:
    build: .
    depends_on:
      - db
    volumes:
      - ./:/go/src/app
    ports:
      - 8100:8100
    environment:
      DB_HOST: mysql
    env_file:
      - ./.env