CREATE DATABASE IF NOT EXISTS `bbs`;
USE bbs;

CREATE TABLE IF NOT EXISTS `bbs`.`user`
(
    `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `salt` CHAR(32) NOT NULL,
    `created_at` DATETIME NOT NULL,
    `updated_at` DATETIME NOT NULL,
    PRIMARY KEY (id)
);